# Generated by Django 5.0.4 on 2024-05-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passage", models.TextField()),
                ("question", models.CharField(max_length=255)),
                ("choices", models.CharField(max_length=1000)),
                ("correct_answer", models.CharField(max_length=100)),
            ],
        ),
    ]
